# Generated by Django 2.0.6 on 2018-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
