# Generated by Django 2.0.6 on 2018-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_registrationmodel_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
