# Generated by Django 2.0.6 on 2018-09-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180923_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationmodel',
            options={'permissions': (('CAN_VIEW_USERS', 'Can view users'),)},
        ),
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registrationmodel',
            name='last_name',
        ),
    ]
