# Generated by Django 2.0.6 on 2018-09-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180923_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationmodel',
            options={},
        ),
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='semester',
            new_name='year',
        ),
    ]
