# Generated by Django 2.0.6 on 2018-09-24 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180924_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
