# Generated by Django 2.0.6 on 2018-09-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20180924_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='branch',
        ),
    ]
