# Generated by Django 2.0.6 on 2018-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20180924_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='coord_id',
            field=models.CharField(default='Nil', max_length=30),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='event',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='txn_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
